spring.application.name=FieldServiceMgmtSystem
# ==========================
# SERVER
# ==========================
server.port=8080

# ==========================
# DATABASE
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/keystone_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG

jwt.secret=ThisIsMyVerySecureSecretKeyForKeystoneApplication123456789

jwt.expiration=86400000


spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB

spring.servlet.multipart.max-request-size=20MB

######################################
# EMAIL CONFIGURATION
######################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=peetlamahesh9182@gmail.com
spring.mail.password=eodthqjyrbwgynhz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true